import type { Establishment, GeoPoint, RentalSpace, RegistrationTopic, Supplier } from '@/types/chatbot.types'

export const CITY_CENTER: GeoPoint = { lat: 8.9475, lng: 125.5406 }

const UNSPLASH = (photoId: string): string =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=480&h=240&q=60`

export const RENTAL_SPACES: RentalSpace[] = [
  {
    id: 'rs-1',
    name: 'Bayanihan Arcade Unit 3B',
    barangay: 'Bayanihan',
    address: 'Montilla Blvd., Bayanihan',
    location: { lat: 8.9492, lng: 125.5432 },
    monthlyRent: 12000,
    areaSqm: 24,
    spaceType: 'retail',
    isAvailable: true,
    suitableFor: ['sari-sari store', 'pharmacy', 'clothing boutique', 'load station'],
    imageUrl: UNSPLASH('photo-1441986300917-64674bd600d8'),
  },
  {
    id: 'rs-2',
    name: 'Obrero Food Alley Stall 12',
    barangay: 'Obrero',
    address: 'J.C. Aquino Ave., Obrero',
    location: { lat: 8.951, lng: 125.5389 },
    monthlyRent: 6500,
    areaSqm: 12,
    spaceType: 'food-stall',
    isAvailable: true,
    suitableFor: ['coffee shop', 'food stall', 'snack house', 'milk tea shop'],
    imageUrl: UNSPLASH('photo-1555396273-367ea4eb4db5'),
  },
  {
    id: 'rs-3',
    name: 'Libertad Tech Hub Suite 204',
    barangay: 'Libertad',
    address: 'CDO Rd., Libertad',
    location: { lat: 8.9568, lng: 125.5371 },
    monthlyRent: 18000,
    areaSqm: 40,
    spaceType: 'office',
    isAvailable: true,
    suitableFor: ['printing services', 'electronics repair', 'tutorial center'],
    imageUrl: UNSPLASH('photo-1497366216548-37526070297c'),
  },
  {
    id: 'rs-4',
    name: 'San Vicente Corner Storefront',
    barangay: 'San Vicente',
    address: 'South Rd., San Vicente',
    location: { lat: 8.9412, lng: 125.5451 },
    monthlyRent: 15000,
    areaSqm: 30,
    spaceType: 'retail',
    isAvailable: true,
    suitableFor: ['grocery', 'hardware', 'bakery', 'water refilling station'],
    imageUrl: UNSPLASH('photo-1441984904996-e0b6ba687e04'),
  },
  {
    id: 'rs-5',
    name: 'Agusan Pequeño Warehouse Bay 2',
    barangay: 'Agusan Pequeño',
    address: 'National Hwy., Agusan Pequeño',
    location: { lat: 8.9367, lng: 125.5298 },
    monthlyRent: 22000,
    areaSqm: 120,
    spaceType: 'warehouse',
    isAvailable: true,
    suitableFor: ['distribution', 'storage', 'supplier depot'],
    imageUrl: UNSPLASH('photo-1553413077-190dd305871c'),
  },
  {
    id: 'rs-6',
    name: 'Baan Riverside Kiosk 5',
    barangay: 'Baan',
    address: 'Riverside Dr., Baan',
    location: { lat: 8.944, lng: 125.548 },
    monthlyRent: 5000,
    areaSqm: 10,
    spaceType: 'food-stall',
    isAvailable: true,
    suitableFor: ['coffee shop', 'snack house', 'flower shop'],
    imageUrl: UNSPLASH('photo-1521017432531-fbd92d768814'),
  },
  {
    id: 'rs-7',
    name: 'Ambago Neighborhood Space',
    barangay: 'Ambago',
    address: 'Doña Francisca St., Ambago',
    location: { lat: 8.9601, lng: 125.5467 },
    monthlyRent: 8000,
    areaSqm: 18,
    spaceType: 'retail',
    isAvailable: true,
    suitableFor: ['sari-sari store', 'salon', 'pharmacy', 'laundry shop'],
    imageUrl: UNSPLASH('photo-1560066984-138dadb4c035'),
  },
  {
    id: 'rs-8',
    name: 'Bonbon Market Row Unit 21',
    barangay: 'Bonbon',
    address: 'Market Rd., Bonbon',
    location: { lat: 8.9545, lng: 125.5523 },
    monthlyRent: 7000,
    areaSqm: 15,
    spaceType: 'retail',
    isAvailable: true,
    suitableFor: ['meat shop', 'vegetable stall', 'grocery'],
    imageUrl: UNSPLASH('photo-1533900298318-6b8da08a523e'),
  },
]

export const SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Butuan Packaging Hub',
    category: 'packaging',
    barangay: 'Obrero',
    location: { lat: 8.9505, lng: 125.5401 },
    servesBusinessTypes: ['sari-sari store', 'grocery', 'bakery', 'restaurant', 'coffee shop'],
  },
  {
    id: 'sup-2',
    name: 'Agusan Fresh Produce Trading',
    category: 'fresh produce',
    barangay: 'Bonbon',
    location: { lat: 8.9538, lng: 125.5501 },
    servesBusinessTypes: ['restaurant', 'coffee shop', 'snack house', 'canteen'],
  },
  {
    id: 'sup-3',
    name: 'NorthMin Coffee Roasters',
    category: 'coffee supply',
    barangay: 'Libertad',
    location: { lat: 8.9575, lng: 125.5355 },
    servesBusinessTypes: ['coffee shop', 'milk tea shop', 'restaurant'],
  },
  {
    id: 'sup-4',
    name: 'Caraga Kitchen Equipment',
    category: 'kitchen equipment',
    barangay: 'San Vicente',
    location: { lat: 8.9425, lng: 125.547 },
    servesBusinessTypes: ['restaurant', 'coffee shop', 'bakery', 'food stall'],
  },
  {
    id: 'sup-5',
    name: 'One Stop Retail Wholesale',
    category: 'wholesale goods',
    barangay: 'Bayanihan',
    location: { lat: 8.9487, lng: 125.5445 },
    servesBusinessTypes: ['sari-sari store', 'pharmacy', 'clothing boutique', 'grocery'],
  },
  {
    id: 'sup-6',
    name: 'PrintPlus Supplies Depot',
    category: 'printing supplies',
    barangay: 'Libertad',
    location: { lat: 8.956, lng: 125.539 },
    servesBusinessTypes: ['printing services', 'tutorial center'],
  },
]

export const ESTABLISHMENTS: Establishment[] = [
  {
    id: 'est-1',
    name: 'Brew & Bean Café',
    category: 'coffee shop',
    barangay: 'Obrero',
    location: { lat: 8.9489, lng: 125.5421 },
    imageUrl: UNSPLASH('photo-1554118811-1e0d58224f24'),
  },
  {
    id: 'est-2',
    name: 'Highland Roast Coffee House',
    category: 'coffee shop',
    barangay: 'Libertad',
    location: { lat: 8.957, lng: 125.5368 },
    imageUrl: UNSPLASH('photo-1501339847302-ac426a4a7cbb'),
  },
  {
    id: 'est-3',
    name: 'Kapehan sa Riverside',
    category: 'coffee shop',
    barangay: 'Baan',
    location: { lat: 8.9447, lng: 125.5492 },
    imageUrl: UNSPLASH('photo-1495474472287-4d71bcdd2085'),
  },
  {
    id: 'est-4',
    name: 'Lutong Bahay Restaurant',
    category: 'restaurant',
    barangay: 'Bayanihan',
    location: { lat: 8.9498, lng: 125.5455 },
    imageUrl: UNSPLASH('photo-1517248135467-4c7edcad34c4'),
  },
  {
    id: 'est-5',
    name: 'Riverside Grill & Dine',
    category: 'restaurant',
    barangay: 'Baan',
    location: { lat: 8.9436, lng: 125.5498 },
    imageUrl: UNSPLASH('photo-1552566626-52f8b828add9'),
  },
  {
    id: 'est-6',
    name: 'Butuan City Department Store',
    category: 'department store',
    barangay: 'Obrero',
    location: { lat: 8.9502, lng: 125.5395 },
    imageUrl: UNSPLASH('photo-1519567241046-7f570eee3ce6'),
  },
  {
    id: 'est-7',
    name: 'Agusan Supermarket',
    category: 'grocery',
    barangay: 'Agusan Pequeño',
    location: { lat: 8.938, lng: 125.531 },
    imageUrl: UNSPLASH('photo-1542838132-92c53300491e'),
  },
  {
    id: 'est-8',
    name: 'Southside Pharmacy',
    category: 'pharmacy',
    barangay: 'San Vicente',
    location: { lat: 8.9418, lng: 125.5443 },
    imageUrl: UNSPLASH('photo-1587854692152-cbe660dbde88'),
  },
  {
    id: 'est-9',
    name: 'Gaisano Department Store',
    category: 'department store',
    barangay: 'Bayanihan',
    location: { lat: 8.9481, lng: 125.5448 },
    imageUrl: UNSPLASH('photo-1472851294608-062f824d29cc'),
  },
  {
    id: 'est-10',
    name: 'Morning Brew Kapehan',
    category: 'coffee shop',
    barangay: 'Ambago',
    location: { lat: 8.9595, lng: 125.5455 },
    imageUrl: UNSPLASH('photo-1447933601403-0c6688de566e'),
  },
]

export const REGISTRATION_TOPICS: RegistrationTopic[] = [
  {
    id: 'reg-1',
    keywords: ['dti', 'business name', 'register business name', 'registration', 'bnrs'],
    question: 'How do I register my business name with the DTI?',
    answer:
      'Register your business name with the DTI through the BNRS (bnrs.dti.gov.ph) or any DTI office. Bring a valid ID and your proposed business name. The certificate of business name registration is valid for 5 years and is required before securing a mayor\'s permit.',
  },
  {
    id: 'reg-2',
    keywords: ['mayor', 'mayors permit', "mayor's permit", 'business permit', 'city hall'],
    question: 'How do I get a mayor\'s / business permit?',
    answer:
      'Apply for a mayor\'s permit at the City Hall Business Permits and Licensing Office after DTI registration. Typical requirements: DTI certificate, barangay clearance, zoning clearance, occupancy permit, community tax certificate, and public liability insurance for certain businesses. Renew every January 20.',
  },
  {
    id: 'reg-3',
    keywords: ['barangay clearance', 'barangay requirement', 'brgy clearance'],
    question: 'How do I get a barangay clearance?',
    answer:
      'Go to the barangay hall where your business will operate. Bring your DTI certificate, a valid ID, and pay the clearance fee. Some barangays require a short inspection of the site before releasing the clearance.',
  },
  {
    id: 'reg-4',
    keywords: ['bir', 'tax', 'tin', 'official receipt', 'invoice'],
    question: 'What are the BIR requirements for a new business?',
    answer:
      'After getting your mayor\'s permit, register with the BIR RDO having jurisdiction over your location within 30 days. Requirements: filled-out BIR Form 1901, mayor\'s permit, DTI certificate, valid ID, and proof of address. You will receive your TIN, then register your books of accounts, official receipts/invoices, and pay the annual registration fee.',
  },
  {
    id: 'reg-5',
    keywords: ['zoning', 'location clearance', 'cenro', 'locational'],
    question: 'Do I need a zoning or locational clearance?',
    answer:
      'Yes. Secure a zoning/locational clearance from the City Planning and Development Office (or CENRO) to confirm your business activity is allowed in that area\'s land-use classification. This is required before the mayor\'s permit is released.',
  },
  {
    id: 'reg-6',
    keywords: ['sss', 'philhealth', 'pag-ibig', 'employees', 'hiring', 'benefits'],
    question: 'What should I do if I plan to hire employees?',
    answer:
      'Register your business with SSS, PhilHealth, and Pag-IBIG as an employer within 30 days of hiring your first employee. You and your employees contribute monthly; remittances are required to keep your permits in good standing.',
  },
  {
    id: 'reg-7',
    keywords: ['renew', 'renewal', 'penalty', 'deadline', 'january'],
    question: 'When and how do I renew my business permits?',
    answer:
      'Renew your mayor\'s permit and barangay clearance annually on or before January 20. Late renewal incurs surcharges and penalties that grow over time, so renew early. BIR registration renews via the annual registration fee every January 31.',
  },
  {
    id: 'reg-8',
    keywords: ['requirement', 'requirements', 'documents', 'checklist', 'start business'],
    question: 'What are the overall requirements to start a business?',
    answer:
      'General checklist: (1) DTI business name registration, (2) barangay clearance, (3) zoning/locational clearance, (4) mayor\'s/business permit, (5) BIR registration, and (6) SSS/PhilHealth/Pag-IBIG employer registration if hiring. Food businesses also need sanitary permits from the City Health Office.',
  },
]
