// Static commercial-space inventory for Butuan City.
//
// The first three entries are the real buildings already carried by the chatbot
// (RENTAL_SPACES in @/services/chatbot/chatbot.static-data) — name, address,
// coordinates, photo and description are pulled straight from there so the two
// features never disagree. Commercial detail (rent bands, unit counts, terms) is
// authored prototype data, as are the remaining listings.
import { RENTAL_SPACES } from '@/services/chatbot/chatbot.static-data'
import type { SpaceListing } from '@/types/smart-analysis.types'

const UNSPLASH = (photoId: string): string =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=640&h=320&q=60`

function fromChatbot(id: string): Partial<SpaceListing> {
  const source = RENTAL_SPACES.find((space) => space.id === id)

  if (!source) {
    return {}
  }

  return {
    name: source.name,
    address: source.address,
    barangay: source.barangay,
    lat: source.location.lat,
    lng: source.location.lng,
    imageUrl: source.imageUrl,
    spaceType: source.spaceType,
    rating: source.rating,
    contactNumber: source.contactNumber,
    description: source.description ?? '',
  }
}

export const SPACE_INVENTORY: SpaceListing[] = [
  {
    id: 'rs-samping-avenue',
    name: 'Samping Avenue',
    address: 'J. C. Aquino Ave, Butuan City, 8600 Agusan del Norte',
    barangay: 'Bayanihan',
    lat: 8.943719846151486,
    lng: 125.5253970459244,
    spaceType: 'office',
    description:
      'Multi-tenant commercial/office building along JC Aquino Avenue with rentable spaces for offices and businesses. Has parking space and security.',
    ...fromChatbot('rs-samping-avenue'),
    sizeBands: ['20-50', '51-100', '101-300'],
    intents: ['rent'],
    unitsAvailable: 6,
    areaSqmMin: 24,
    areaSqmMax: 180,
    rentMin: 9000,
    rentMax: 38000,
    amenities: ['Parking', '24/7 security', 'Fibre-ready', 'Backup generator', 'Comfort rooms'],
    terms: [
      { label: 'Deposit', value: '2 months' },
      { label: 'Advance', value: '1 month' },
      { label: 'Minimum lease', value: '12 months' },
      { label: 'Association dues', value: '₱45 / sqm per month' },
      { label: 'Turnover', value: 'Bare shell, 30-day fit-out grace' },
    ],
  },
  {
    id: 'rs-intino-2',
    name: 'RC Intino Building 2',
    address: 'North Montilla Boulevard, Ong Yiu',
    barangay: 'Ong Yiu',
    lat: 8.957163,
    lng: 125.540412,
    spaceType: 'office',
    description: 'Has parking and affordable rental space suitable for offices and businesses.',
    ...fromChatbot('rs-intino-2'),
    sizeBands: ['under-20', '20-50', '51-100'],
    intents: ['rent'],
    unitsAvailable: 4,
    areaSqmMin: 16,
    areaSqmMax: 90,
    rentMin: 6500,
    rentMax: 22000,
    amenities: ['Parking', 'Water and power sub-meter', 'Street frontage', 'CCTV'],
    terms: [
      { label: 'Deposit', value: '2 months' },
      { label: 'Advance', value: '1 month' },
      { label: 'Minimum lease', value: '6 months' },
      { label: 'Association dues', value: 'None' },
      { label: 'Turnover', value: 'Painted, tiled, with lighting' },
    ],
  },
  {
    id: 'rs-ps-arcade',
    name: 'PS Arcade',
    address: 'Jose Rosales Ave., Imadejas',
    barangay: 'Imadejas',
    lat: 8.94676684700114,
    lng: 125.53137829822042,
    spaceType: 'retail',
    description:
      'Commercial arcade along Jose Rosales Avenue with rentable spaces for shops and offices.',
    ...fromChatbot('rs-ps-arcade'),
    sizeBands: ['under-20', '20-50'],
    intents: ['rent'],
    unitsAvailable: 7,
    areaSqmMin: 12,
    areaSqmMax: 48,
    rentMin: 5500,
    rentMax: 18000,
    amenities: ['Arcade foot traffic', 'Shared comfort rooms', 'Roll-up shutters', 'Signage band'],
    terms: [
      { label: 'Deposit', value: '2 months' },
      { label: 'Advance', value: '1 month' },
      { label: 'Minimum lease', value: '12 months' },
      { label: 'Association dues', value: '₱1,200 per month' },
      { label: 'Turnover', value: 'Bare, with electrical rough-in' },
    ],
  },
  {
    id: 'sp-libertad-strip',
    name: 'Libertad Commercial Strip',
    address: 'Libertad Rd., Butuan City',
    barangay: 'Libertad',
    lat: 8.9598,
    lng: 125.5318,
    imageUrl: UNSPLASH('photo-1441986300917-64674bd600d8'),
    spaceType: 'retail',
    description:
      'Roadside retail row facing the Libertad market catchment. Inline units with shared parking apron and high weekend walk-in volume.',
    sizeBands: ['20-50', '51-100'],
    intents: ['rent'],
    unitsAvailable: 5,
    areaSqmMin: 28,
    areaSqmMax: 96,
    rentMin: 12000,
    rentMax: 30000,
    amenities: ['Shared parking apron', 'Loading bay', 'Three-phase power', 'Night security'],
    terms: [
      { label: 'Deposit', value: '3 months' },
      { label: 'Advance', value: '1 month' },
      { label: 'Minimum lease', value: '24 months' },
      { label: 'Association dues', value: '₱60 / sqm per month' },
      { label: 'Turnover', value: 'Bare shell' },
    ],
  },
  {
    id: 'sp-villa-kananga-kiosks',
    name: 'Villa Kananga Kiosk Row',
    address: 'J.C. Aquino Ave., Villa Kananga',
    barangay: 'Villa Kananga',
    lat: 8.9557,
    lng: 125.5529,
    imageUrl: UNSPLASH('photo-1567521464027-f127ff144326'),
    spaceType: 'food-stall',
    description:
      'Purpose-built kiosk row beside a campus gate. Sized for beverage, snack and load counters, with a shared dining deck.',
    sizeBands: ['under-20'],
    intents: ['rent'],
    unitsAvailable: 9,
    areaSqmMin: 6,
    areaSqmMax: 18,
    rentMin: 4500,
    rentMax: 12000,
    amenities: ['Shared dining deck', 'Grease trap', 'Sub-metered utilities', 'Student foot traffic'],
    terms: [
      { label: 'Deposit', value: '2 months' },
      { label: 'Advance', value: '1 month' },
      { label: 'Minimum lease', value: '6 months' },
      { label: 'Association dues', value: '₱800 per month' },
      { label: 'Turnover', value: 'Counter, sink and power provided' },
    ],
  },
  {
    id: 'sp-montilla-groundfloor',
    name: 'Montilla Boulevard Ground Floor',
    address: 'Montilla Blvd, Golden Ribbon',
    barangay: 'Golden Ribbon',
    lat: 8.9524,
    lng: 125.5381,
    imageUrl: UNSPLASH('photo-1497366216548-37526070297c'),
    spaceType: 'retail',
    description:
      'Ground-floor commercial space on the central boulevard. Wide glass frontage, suited to pharmacy, clinic or specialty retail.',
    sizeBands: ['51-100', '101-300'],
    intents: ['rent', 'sale'],
    unitsAvailable: 3,
    areaSqmMin: 65,
    areaSqmMax: 240,
    rentMin: 28000,
    rentMax: 78000,
    salePriceMin: 6800000,
    salePriceMax: 18500000,
    rating: 4.2,
    contactNumber: '0917 622 4410',
    amenities: ['Glass frontage', 'Air-conditioning provision', 'Parking', 'Elevator access'],
    terms: [
      { label: 'Deposit', value: '3 months' },
      { label: 'Advance', value: '2 months' },
      { label: 'Minimum lease', value: '36 months' },
      { label: 'Association dues', value: '₱85 / sqm per month' },
      { label: 'Turnover', value: 'Warm shell with ceiling and lighting' },
    ],
  },
  {
    id: 'sp-doongan-warehouse',
    name: 'Doongan Warehouse Annex',
    address: 'Doongan Rd., Butuan City',
    barangay: 'Doongan',
    lat: 8.9641,
    lng: 125.5481,
    imageUrl: UNSPLASH('photo-1553413077-190dd305871c'),
    spaceType: 'warehouse',
    description:
      'Clear-span warehouse with a hardstand yard and truck access, suited to cold chain, distribution or light manufacturing.',
    sizeBands: ['300-plus'],
    intents: ['rent', 'sale'],
    unitsAvailable: 2,
    areaSqmMin: 420,
    areaSqmMax: 1200,
    rentMin: 85000,
    rentMax: 240000,
    salePriceMin: 18000000,
    salePriceMax: 46000000,
    contactNumber: '0918 445 7729',
    amenities: ['Truck hardstand', 'Clear-span 7 m', 'Three-phase power', 'Perimeter fence', 'Guardhouse'],
    terms: [
      { label: 'Deposit', value: '3 months' },
      { label: 'Advance', value: '2 months' },
      { label: 'Minimum lease', value: '36 months' },
      { label: 'Association dues', value: 'None' },
      { label: 'Turnover', value: 'As-is, buyer fit-out' },
    ],
  },
  {
    id: 'sp-langihan-lot',
    name: 'Langihan Road Commercial Lot',
    address: 'Langihan Rd., Butuan City',
    barangay: 'Langihan',
    lat: 8.9581,
    lng: 125.5611,
    imageUrl: UNSPLASH('photo-1500382017468-9049fed747ef'),
    spaceType: 'warehouse',
    description:
      'Titled commercial lot on the Langihan corridor, suited to build-to-suit development or an equipment yard.',
    sizeBands: ['300-plus'],
    intents: ['sale'],
    unitsAvailable: 1,
    areaSqmMin: 900,
    areaSqmMax: 900,
    salePriceMin: 12500000,
    salePriceMax: 12500000,
    contactNumber: '0920 331 8846',
    amenities: ['Clean title', 'Road frontage 28 m', 'Utilities at the property line', 'Level grade'],
    terms: [
      { label: 'Payment', value: 'Cash or bank financing' },
      { label: 'Reservation', value: '₱100,000, deductible' },
      { label: 'Transfer costs', value: 'Split 50 / 50' },
      { label: 'Zoning', value: 'Commercial C-2' },
      { label: 'Turnover', value: 'Clean and vacant on full payment' },
    ],
  },
  {
    id: 'sp-poblacion-shophouse',
    name: 'Poblacion Shophouse Units',
    address: 'San Francisco St., Poblacion',
    barangay: 'Poblacion',
    lat: 8.9465,
    lng: 125.5424,
    imageUrl: UNSPLASH('photo-1555636222-cae831e670b3'),
    spaceType: 'retail',
    description:
      'Two-storey shophouse units in the old commercial core — retail below, stockroom or staff quarters above.',
    sizeBands: ['20-50', '51-100'],
    intents: ['rent', 'sale'],
    unitsAvailable: 4,
    areaSqmMin: 32,
    areaSqmMax: 88,
    rentMin: 14000,
    rentMax: 34000,
    salePriceMin: 3900000,
    salePriceMax: 9200000,
    rating: 3.9,
    amenities: ['Two storeys', 'Roll-up shutter', 'Mezzanine stockroom', 'Walk-in market traffic'],
    terms: [
      { label: 'Deposit', value: '2 months' },
      { label: 'Advance', value: '1 month' },
      { label: 'Minimum lease', value: '12 months' },
      { label: 'Association dues', value: 'None' },
      { label: 'Turnover', value: 'Painted, tiled ground floor' },
    ],
  },
  {
    id: 'sp-ampayon-roadside',
    name: 'Ampayon Roadside Units',
    address: 'Butuan – Cagayan Rd., Ampayon',
    barangay: 'Ampayon',
    lat: 8.9579,
    lng: 125.5974,
    imageUrl: UNSPLASH('photo-1524230572899-a752b3835840'),
    spaceType: 'retail',
    description:
      'Highway-facing units near the university belt, with deep parking and space for a service bay or drive-through.',
    sizeBands: ['51-100', '101-300'],
    intents: ['rent'],
    unitsAvailable: 3,
    areaSqmMin: 70,
    areaSqmMax: 260,
    rentMin: 22000,
    rentMax: 62000,
    contactNumber: '0995 774 2218',
    amenities: ['Deep parking', 'Highway frontage', 'Service bay provision', 'Three-phase power'],
    terms: [
      { label: 'Deposit', value: '3 months' },
      { label: 'Advance', value: '1 month' },
      { label: 'Minimum lease', value: '24 months' },
      { label: 'Association dues', value: '₱50 / sqm per month' },
      { label: 'Turnover', value: 'Bare shell' },
    ],
  },
]
