// Static supplier directory for Butuan City, grouped by the business category
// the supplier serves. Names, contacts and coordinates are authored prototype
// data — no live records, no verification. Field-check before relying on any of it.
import type { SupplierRecord } from '@/views/(user)/map/types/smart-analysis.types'

export const SUPPLIER_DIRECTORY: Record<string, SupplierRecord[]> = {
  'food-beverage': [
    {
      name: 'JC Trading Butuan',
      trade: 'General Wholesale / Dry Goods',
      address: 'P. Casal St., Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 342 1234',
      email: 'jctrading@gmail.com',
      lat: 8.9488,
      lng: 125.5415,
      specialties: ['Canned goods', 'Condiments and seasonings', 'Rice and flour', 'Cooking oil'],
      bestFor: ['restaurant', 'fast-food', 'food-stall-carinderia', 'bakery', 'bbq-grill'],
      minimumOrder: '₱5,000 per delivery',
      paymentTerms: 'Cash, 15-day terms for accredited accounts',
      delivery: 'Free within 5 km, ₱350 beyond',
      leadTime: 'Same day for stocked items, 2 – 3 days otherwise',
      operatingHours: 'Mon – Sat, 7:00 AM – 6:00 PM',
      yearsOperating: 18,
    },
    {
      name: 'Butuan City Public Market Wholesalers',
      trade: 'Wet / Dry Goods & Agricultural',
      address: 'Lihis St., Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 341 5678',
      email: 'bcpmarket@butuan.gov.ph',
      lat: 8.9472,
      lng: 125.5401,
      specialties: ['Fresh produce', 'Meat and poultry', 'Seafood', 'Bulk vegetables'],
      bestFor: ['food-stall-carinderia', 'restaurant', 'bbq-grill', 'catering-services', 'fruit-stand'],
      minimumOrder: 'None — per-kilo bagsakan pricing',
      paymentTerms: 'Cash on pickup',
      delivery: 'Buyer-arranged, tricycle and multicab hire on site',
      leadTime: 'Immediate, daily 4:00 AM bagsakan',
      operatingHours: 'Daily, 4:00 AM – 6:00 PM',
      yearsOperating: 40,
    },
    {
      name: 'D&J Wholesale Center',
      trade: 'Beverages, Snacks & Personal Care',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 225 9900',
      email: 'dj.wholesale@yahoo.com',
      lat: 8.9501,
      lng: 125.5438,
      specialties: ['Softdrinks and juices', 'Snack packs', 'Coffee and creamer', 'Disposables'],
      bestFor: ['cafe-coffee-shop', 'milk-tea-beverage-shop', 'sari-sari-store', 'fast-food'],
      minimumOrder: '₱3,000 per delivery',
      paymentTerms: 'Cash, cheque for regular accounts',
      delivery: 'Free within Butuan proper',
      leadTime: '1 – 2 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:30 PM',
      yearsOperating: 12,
    },
    {
      name: 'Caraga Cold Chain & Abattoir Supply',
      trade: 'Frozen Meat & Cold Storage',
      address: 'Doongan Rd., Butuan City',
      barangay: 'Doongan',
      phone: '+63 85 815 3321',
      email: 'caragacoldchain@gmail.com',
      lat: 8.9631,
      lng: 125.5487,
      specialties: ['Frozen pork and chicken', 'Processed meats', 'Ice supply', 'Cold storage rental'],
      bestFor: ['restaurant', 'fast-food', 'bbq-grill', 'catering-services', 'food-processing'],
      minimumOrder: '₱8,000 or 20 kg per item',
      paymentTerms: '30-day terms with deposit',
      delivery: 'Refrigerated van, free above ₱15,000',
      leadTime: '1 – 3 days',
      operatingHours: 'Mon – Sat, 6:00 AM – 5:00 PM',
      yearsOperating: 9,
    },
    {
      name: 'Agusan Bakers Ingredients Depot',
      trade: 'Baking & Pastry Ingredients',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 342 6612',
      email: 'agusanbakersdepot@gmail.com',
      lat: 8.9556,
      lng: 125.5533,
      specialties: ['Bread flour', 'Yeast and improvers', 'Fillings and glazes', 'Packaging'],
      bestFor: ['bakery', 'cafe-coffee-shop', 'catering-services', 'milk-tea-beverage-shop'],
      minimumOrder: '₱2,500 per delivery',
      paymentTerms: 'Cash, 7-day terms for regulars',
      delivery: 'Free within 8 km',
      leadTime: 'Same day to 2 days',
      operatingHours: 'Mon – Sat, 7:30 AM – 6:00 PM',
      yearsOperating: 15,
    },
  ],

  'retail-shopping': [
    {
      name: 'Metro Butuan Distributors',
      trade: 'FMCG & General Merchandise',
      address: 'Libertad, Butuan City',
      barangay: 'Libertad',
      phone: '+63 85 225 4455',
      email: 'metrobutuan.dist@gmail.com',
      lat: 8.9592,
      lng: 125.5305,
      specialties: ['Household goods', 'Personal care', 'Packaged food', 'Cleaning supplies'],
      bestFor: ['grocery-minimart', 'sari-sari-store', 'gift-shop-souvenir'],
      minimumOrder: '₱10,000 per delivery',
      paymentTerms: '30-day terms for accredited retailers',
      delivery: 'Route delivery twice weekly',
      leadTime: '2 – 4 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:00 PM',
      yearsOperating: 21,
    },
    {
      name: 'Butuan Hardware & Industrial Supply',
      trade: 'Hardware, Construction & Industrial',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Golden Ribbon',
      phone: '+63 85 341 8890',
      email: 'butuanhardware@gmail.com',
      lat: 8.9527,
      lng: 125.5372,
      specialties: ['Power tools', 'Plumbing fittings', 'Electrical supplies', 'Paint'],
      bestFor: ['hardware-store', 'appliance-store', 'furniture-store'],
      minimumOrder: '₱7,500 per delivery',
      paymentTerms: 'Cash, cheque, 15-day terms',
      delivery: 'Free within 10 km',
      leadTime: '1 – 5 days depending on stock',
      operatingHours: 'Mon – Sat, 7:30 AM – 6:00 PM',
      yearsOperating: 26,
    },
    {
      name: 'Northern Mindanao Apparel Traders',
      trade: 'Apparel, Footwear & Textiles',
      address: 'San Francisco St., Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 342 2210',
      email: 'nmapparel.trade@gmail.com',
      lat: 8.9463,
      lng: 125.5428,
      specialties: ['Ready-to-wear bales', 'Uniform fabric', 'Footwear lots', 'Accessories'],
      bestFor: ['clothing-apparel-store', 'footwear-shop', 'gift-shop-souvenir'],
      minimumOrder: '₱6,000 or one bale',
      paymentTerms: 'Cash on pickup, 50% deposit for bulk',
      delivery: 'Courier consolidation, buyer pays freight',
      leadTime: '3 – 7 days',
      operatingHours: 'Mon – Sat, 8:30 AM – 6:00 PM',
      yearsOperating: 11,
    },
    {
      name: 'Caraga Electronics Wholesale',
      trade: 'Consumer Electronics & Accessories',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 815 7742',
      email: 'caraga.electronics@gmail.com',
      lat: 8.9548,
      lng: 125.5521,
      specialties: ['Mobile accessories', 'Small appliances', 'Cables and chargers', 'Audio'],
      bestFor: ['electronics-shop', 'appliance-store', 'mobile-phone-shop-and-repair'],
      minimumOrder: '₱5,000 per delivery',
      paymentTerms: 'Cash, 15-day terms with deposit',
      delivery: 'Free within Butuan proper',
      leadTime: '2 – 5 days',
      operatingHours: 'Mon – Sat, 9:00 AM – 6:00 PM',
      yearsOperating: 8,
    },
    {
      name: 'Agusan Book & School Supply Depot',
      trade: 'Books, Paper & School Supplies',
      address: 'Langihan Rd., Butuan City',
      barangay: 'Langihan',
      phone: '+63 85 341 3367',
      email: 'agusanbookdepot@gmail.com',
      lat: 8.9578,
      lng: 125.5596,
      specialties: ['Notebooks and paper', 'Art materials', 'Textbooks', 'Office consumables'],
      bestFor: ['bookstore-school-supplies', 'printing-photocopy-shop', 'gift-shop-souvenir'],
      minimumOrder: '₱3,000 per delivery',
      paymentTerms: 'Cash, purchase orders honoured for schools',
      delivery: 'Free within 6 km',
      leadTime: '1 – 3 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:30 PM',
      yearsOperating: 17,
    },
  ],

  'services-professional': [
    {
      name: 'Butuan Office Systems Supply',
      trade: 'Office Equipment & Consumables',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 342 9915',
      email: 'butuanofficesystems@gmail.com',
      lat: 8.9509,
      lng: 125.5423,
      specialties: ['Toner and ink', 'Bond paper', 'Copiers and printers', 'Service contracts'],
      bestFor: ['printing-photocopy-shop', 'accounting-tax-service', 'legal-services-notary'],
      minimumOrder: '₱2,500 per delivery',
      paymentTerms: 'Cash, 30-day terms for corporate accounts',
      delivery: 'Free within Butuan proper',
      leadTime: 'Same day to 3 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:30 PM',
      yearsOperating: 14,
    },
    {
      name: 'Caraga Print & Signage Works',
      trade: 'Large-Format Printing & Signage',
      address: 'Villa Kananga, Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 815 2204',
      email: 'caragaprintworks@gmail.com',
      lat: 8.9561,
      lng: 125.5548,
      specialties: ['Tarpaulin printing', 'Acrylic signage', 'Vehicle wraps', 'Sticker cutting'],
      bestFor: ['advertising-agency', 'printing-photocopy-shop', 'event-coordination'],
      minimumOrder: '₱1,500 per job',
      paymentTerms: '50% down payment, balance on release',
      delivery: 'Pickup, delivery for bulk orders',
      leadTime: '1 – 4 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 7:00 PM',
      yearsOperating: 10,
    },
    {
      name: 'Agusan Events & Rentals Hub',
      trade: 'Event Furniture, AV & Styling',
      address: 'Baan Km. 3, Butuan City',
      barangay: 'Baan',
      phone: '+63 85 342 4478',
      email: 'agusaneventshub@gmail.com',
      lat: 8.9403,
      lng: 125.5288,
      specialties: ['Tables and chairs', 'Sound and lighting', 'Tents and staging', 'Styling props'],
      bestFor: ['event-coordination', 'advertising-agency', 'travel-agency'],
      minimumOrder: '₱5,000 per booking',
      paymentTerms: '50% reservation fee, balance before pull-out',
      delivery: 'Delivery and setup included within 15 km',
      leadTime: 'Book 3 – 14 days ahead',
      operatingHours: 'Mon – Sun, 8:00 AM – 6:00 PM',
      yearsOperating: 7,
    },
    {
      name: 'Butuan Business Forms & Records',
      trade: 'Business Forms, Receipts & Filing',
      address: 'P. Burgos St., Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 341 6690',
      email: 'butuanbusinessforms@gmail.com',
      lat: 8.9481,
      lng: 125.5392,
      specialties: ['BIR-registered receipts', 'Carbonless forms', 'Filing systems', 'Rubber stamps'],
      bestFor: ['accounting-tax-service', 'legal-services-notary', 'pawnshop', 'money-remittance'],
      minimumOrder: '₱1,800 per job',
      paymentTerms: 'Cash, 15-day terms for retainers',
      delivery: 'Free within Butuan proper',
      leadTime: '3 – 7 days for printed forms',
      operatingHours: 'Mon – Fri, 8:00 AM – 5:00 PM',
      yearsOperating: 23,
    },
    {
      name: 'Caraga Security & Cash Handling Supply',
      trade: 'Security Equipment & Cash Handling',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Golden Ribbon',
      phone: '+63 85 815 8823',
      email: 'caragasecuritysupply@gmail.com',
      lat: 8.9534,
      lng: 125.5461,
      specialties: ['Safes and vaults', 'Bill counters', 'CCTV kits', 'Alarm systems'],
      bestFor: ['pawnshop', 'money-remittance', 'insurance-agency', 'cctv-security-installation'],
      minimumOrder: '₱8,000 per order',
      paymentTerms: 'Cash, financing available above ₱50,000',
      delivery: 'Delivery and installation quoted per site',
      leadTime: '3 – 10 days',
      operatingHours: 'Mon – Sat, 8:30 AM – 5:30 PM',
      yearsOperating: 13,
    },
  ],

  'health-wellness': [
    {
      name: 'Caraga Pharma Distributors',
      trade: 'Pharmaceutical Wholesale',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 342 7001',
      email: 'caragapharma.dist@gmail.com',
      lat: 8.9553,
      lng: 125.5512,
      specialties: ['Generic medicines', 'Branded pharmaceuticals', 'OTC lines', 'Vitamins'],
      bestFor: ['pharmacy', 'medical-clinic', 'dental-clinic', 'dialysis-center'],
      minimumOrder: '₱15,000 per delivery',
      paymentTerms: '30 – 60 day terms for licensed outlets',
      delivery: 'Free, twice-weekly route',
      leadTime: '2 – 4 days',
      operatingHours: 'Mon – Fri, 8:00 AM – 5:00 PM',
      yearsOperating: 19,
    },
    {
      name: 'Butuan Medical Equipment Center',
      trade: 'Medical Devices & Consumables',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Golden Ribbon',
      phone: '+63 85 341 4432',
      email: 'butuanmedequip@gmail.com',
      lat: 8.9519,
      lng: 125.5389,
      specialties: ['Diagnostic devices', 'Dental units', 'Disposables and PPE', 'Calibration service'],
      bestFor: ['medical-clinic', 'dental-clinic', 'optical-clinic', 'veterinary-clinic', 'dialysis-center'],
      minimumOrder: '₱10,000 per order',
      paymentTerms: 'Cash, leasing available for equipment',
      delivery: 'Delivery and installation included',
      leadTime: '5 – 21 days for equipment',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:00 PM',
      yearsOperating: 16,
    },
    {
      name: 'Agusan Beauty & Salon Supply',
      trade: 'Salon, Spa & Beauty Products',
      address: 'San Francisco St., Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 225 3318',
      email: 'agusanbeautysupply@gmail.com',
      lat: 8.9469,
      lng: 125.5419,
      specialties: ['Hair colour and treatments', 'Salon equipment', 'Spa consumables', 'Nail care'],
      bestFor: ['salon-barbershop', 'spa-and-massage', 'wellness-yoga-studio'],
      minimumOrder: '₱2,000 per delivery',
      paymentTerms: 'Cash, 7-day terms for regulars',
      delivery: 'Free within 6 km',
      leadTime: '1 – 3 days',
      operatingHours: 'Mon – Sat, 9:00 AM – 6:30 PM',
      yearsOperating: 12,
    },
    {
      name: 'FitSource Mindanao',
      trade: 'Fitness Equipment & Supplements',
      address: 'Libertad, Butuan City',
      barangay: 'Libertad',
      phone: '+63 85 815 6674',
      email: 'fitsource.mindanao@gmail.com',
      lat: 8.9601,
      lng: 125.5327,
      specialties: ['Strength equipment', 'Cardio machines', 'Rubber flooring', 'Supplements'],
      bestFor: ['gym-fitness-center', 'wellness-yoga-studio', 'sports-complex'],
      minimumOrder: '₱20,000 per order',
      paymentTerms: '50% down payment, balance on delivery',
      delivery: 'Freight from Cagayan de Oro, install quoted separately',
      leadTime: '7 – 30 days',
      operatingHours: 'Mon – Sat, 9:00 AM – 6:00 PM',
      yearsOperating: 6,
    },
    {
      name: 'Butuan Clinical Reagents Supply',
      trade: 'Laboratory Reagents & Glassware',
      address: 'Doongan, Butuan City',
      barangay: 'Doongan',
      phone: '+63 85 342 8845',
      email: 'butuanreagents@gmail.com',
      lat: 8.9648,
      lng: 125.5464,
      specialties: ['Clinical reagents', 'Test kits', 'Glassware', 'Cold-chain handling'],
      bestFor: ['medical-clinic', 'dialysis-center', 'veterinary-clinic'],
      minimumOrder: '₱12,000 per delivery',
      paymentTerms: '30-day terms for accredited facilities',
      delivery: 'Temperature-controlled delivery included',
      leadTime: '3 – 10 days',
      operatingHours: 'Mon – Fri, 8:00 AM – 5:00 PM',
      yearsOperating: 11,
    },
  ],

  automotive: [
    {
      name: 'Butuan Auto Parts Central',
      trade: 'Automotive Parts & Accessories',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 342 1180',
      email: 'butuanautoparts@gmail.com',
      lat: 8.9544,
      lng: 125.5539,
      specialties: ['Engine parts', 'Filters and belts', 'Suspension', 'Body parts'],
      bestFor: ['auto-repair-shop', 'auto-parts-store', 'motor-motorcycle-shop', 'auto-detailing'],
      minimumOrder: '₱4,000 per delivery',
      paymentTerms: 'Cash, 15-day terms for shops',
      delivery: 'Free within Butuan proper',
      leadTime: 'Same day to 5 days',
      operatingHours: 'Mon – Sat, 7:30 AM – 6:00 PM',
      yearsOperating: 22,
    },
    {
      name: 'Caraga Lubricants & Batteries',
      trade: 'Lubricants, Batteries & Chemicals',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Golden Ribbon',
      phone: '+63 85 341 7729',
      email: 'caragalubes@gmail.com',
      lat: 8.9522,
      lng: 125.5364,
      specialties: ['Engine oil', 'Batteries', 'Coolants', 'Car care chemicals'],
      bestFor: ['auto-repair-shop', 'car-wash', 'auto-detailing', 'trucking-hauling'],
      minimumOrder: '₱6,000 per delivery',
      paymentTerms: 'Cash, 30-day terms for fleet accounts',
      delivery: 'Free above ₱15,000',
      leadTime: '1 – 3 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:30 PM',
      yearsOperating: 15,
    },
    {
      name: 'Agusan Tire & Rim Depot',
      trade: 'Tires, Rims & Vulcanizing Supply',
      address: 'Langihan Rd., Butuan City',
      barangay: 'Langihan',
      phone: '+63 85 815 4416',
      email: 'agusantiredepot@gmail.com',
      lat: 8.9585,
      lng: 125.5631,
      specialties: ['Passenger and truck tires', 'Alloy rims', 'Patching compounds', 'Balancing weights'],
      bestFor: ['vulcanizing-tire-shop', 'auto-repair-shop', 'trucking-hauling', 'towing-service'],
      minimumOrder: '₱7,000 or 4 tires',
      paymentTerms: 'Cash, cheque for fleet buyers',
      delivery: 'Free within 10 km',
      leadTime: '1 – 7 days',
      operatingHours: 'Mon – Sat, 7:00 AM – 6:00 PM',
      yearsOperating: 18,
    },
    {
      name: 'Northern Caraga Motorcycle Supply',
      trade: 'Motorcycle Parts & Accessories',
      address: 'Ampayon, Butuan City',
      barangay: 'Ampayon',
      phone: '+63 85 342 3392',
      email: 'ncmotorsupply@gmail.com',
      lat: 8.9576,
      lng: 125.5967,
      specialties: ['Motorcycle spares', 'Helmets and gear', 'Chains and sprockets', 'Tuning parts'],
      bestFor: ['motor-motorcycle-shop', 'auto-parts-store', 'car-accessories-store'],
      minimumOrder: '₱3,500 per delivery',
      paymentTerms: 'Cash, 7-day terms for regulars',
      delivery: 'Free within 8 km',
      leadTime: '1 – 4 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 6:00 PM',
      yearsOperating: 9,
    },
    {
      name: 'Butuan Heavy Equipment Parts',
      trade: 'Truck & Heavy Equipment Parts',
      address: 'Bancasi, Butuan City',
      barangay: 'Bancasi',
      phone: '+63 85 225 7761',
      email: 'butuanheavyparts@gmail.com',
      lat: 8.9498,
      lng: 125.4788,
      specialties: ['Truck spares', 'Hydraulic parts', 'Heavy-duty filters', 'Welding consumables'],
      bestFor: ['trucking-hauling', 'towing-service', 'auto-repair-shop', 'equipment-rental'],
      minimumOrder: '₱12,000 per order',
      paymentTerms: '30-day terms for corporate fleets',
      delivery: 'Flatbed delivery quoted per order',
      leadTime: '3 – 14 days',
      operatingHours: 'Mon – Sat, 7:30 AM – 5:00 PM',
      yearsOperating: 14,
    },
  ],

  'education-training': [
    {
      name: 'Agusan Book & School Supply Depot',
      trade: 'Books, Paper & School Supplies',
      address: 'Langihan Rd., Butuan City',
      barangay: 'Langihan',
      phone: '+63 85 341 3367',
      email: 'agusanbookdepot@gmail.com',
      lat: 8.9578,
      lng: 125.5596,
      specialties: ['Textbooks', 'Workbooks', 'Art materials', 'Classroom consumables'],
      bestFor: ['tutorial-center', 'review-center', 'daycare-preschool', 'language-school'],
      minimumOrder: '₱3,000 per delivery',
      paymentTerms: 'Cash, purchase orders honoured for schools',
      delivery: 'Free within 6 km',
      leadTime: '1 – 3 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:30 PM',
      yearsOperating: 17,
    },
    {
      name: 'Butuan Classroom Furniture Works',
      trade: 'School Furniture & Fixtures',
      address: 'Baan Km. 3, Butuan City',
      barangay: 'Baan',
      phone: '+63 85 342 5540',
      email: 'butuanclassroomworks@gmail.com',
      lat: 8.9391,
      lng: 125.5271,
      specialties: ['Armchairs and tables', 'Whiteboards', 'Cabinets', 'Custom fabrication'],
      bestFor: ['tutorial-center', 'review-center', 'vocational-tech-school', 'skills-training-center'],
      minimumOrder: '10 units per item',
      paymentTerms: '50% down payment, balance on delivery',
      delivery: 'Delivery and assembly included within 20 km',
      leadTime: '7 – 21 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:00 PM',
      yearsOperating: 20,
    },
    {
      name: 'Caraga EdTech Solutions',
      trade: 'Learning Technology & AV',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 815 9902',
      email: 'caragaedtech@gmail.com',
      lat: 8.9559,
      lng: 125.5526,
      specialties: ['Projectors and screens', 'Laptop bundles', 'LMS setup', 'Language lab kits'],
      bestFor: ['online-e-learning-center', 'language-school', 'vocational-tech-school', 'review-center'],
      minimumOrder: '₱15,000 per order',
      paymentTerms: 'Cash, financing for institutional accounts',
      delivery: 'Delivery and commissioning included',
      leadTime: '5 – 20 days',
      operatingHours: 'Mon – Fri, 8:30 AM – 5:30 PM',
      yearsOperating: 7,
    },
    {
      name: 'Butuan Technical Training Supply',
      trade: 'TESDA Tools & Training Consumables',
      address: 'Libertad, Butuan City',
      barangay: 'Libertad',
      phone: '+63 85 341 2287',
      email: 'butuantechsupply@gmail.com',
      lat: 8.9608,
      lng: 125.5312,
      specialties: ['Welding trainers', 'Electrical kits', 'Automotive trainers', 'Safety gear'],
      bestFor: ['vocational-tech-school', 'skills-training-center', 'driving-school'],
      minimumOrder: '₱10,000 per order',
      paymentTerms: '30-day terms for accredited centres',
      delivery: 'Free within Butuan proper',
      leadTime: '7 – 30 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:00 PM',
      yearsOperating: 12,
    },
    {
      name: 'Little Learners Play Supply',
      trade: 'Early Childhood Materials',
      address: 'Doongan, Butuan City',
      barangay: 'Doongan',
      phone: '+63 85 225 6613',
      email: 'littlelearners.butuan@gmail.com',
      lat: 8.9639,
      lng: 125.5478,
      specialties: ['Play equipment', 'Manipulatives', 'Safety mats', 'Storybooks'],
      bestFor: ['daycare-preschool', 'child-development-center', 'tutorial-center'],
      minimumOrder: '₱4,000 per delivery',
      paymentTerms: 'Cash, 15-day terms for schools',
      delivery: 'Free within 8 km',
      leadTime: '3 – 10 days',
      operatingHours: 'Mon – Sat, 8:30 AM – 5:00 PM',
      yearsOperating: 6,
    },
  ],

  'entertainment-recreation': [
    {
      name: 'Caraga Sound & Lighting Supply',
      trade: 'Pro Audio, Lighting & Staging',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 342 4409',
      email: 'caragasoundlights@gmail.com',
      lat: 8.9505,
      lng: 125.5446,
      specialties: ['Speakers and amps', 'Stage lighting', 'Mixers', 'Videoke systems'],
      bestFor: ['videoke-ktv-bar', 'events-place-function-hall', 'movie-cinema', 'amusement-arcade'],
      minimumOrder: '₱10,000 per order',
      paymentTerms: 'Cash, installment for systems above ₱80,000',
      delivery: 'Delivery and tuning included within 20 km',
      leadTime: '3 – 14 days',
      operatingHours: 'Mon – Sat, 9:00 AM – 7:00 PM',
      yearsOperating: 13,
    },
    {
      name: 'Butuan Gaming Hardware Hub',
      trade: 'Gaming PCs, Consoles & Networking',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 815 3390',
      email: 'butuangaminghub@gmail.com',
      lat: 8.9551,
      lng: 125.5518,
      specialties: ['Gaming rigs', 'Monitors and peripherals', 'Network switches', 'Café management software'],
      bestFor: ['gaming-internet-cafe', 'amusement-arcade', 'escape-room'],
      minimumOrder: '₱25,000 per order',
      paymentTerms: '50% down payment, balance on installation',
      delivery: 'Delivery and setup included',
      leadTime: '7 – 21 days',
      operatingHours: 'Mon – Sat, 10:00 AM – 8:00 PM',
      yearsOperating: 8,
    },
    {
      name: 'Agusan Sports Equipment Supply',
      trade: 'Sports & Recreation Equipment',
      address: 'Libertad, Butuan City',
      barangay: 'Libertad',
      phone: '+63 85 341 8852',
      email: 'agusansportsupply@gmail.com',
      lat: 8.9597,
      lng: 125.5341,
      specialties: ['Billiard tables', 'Bowling supplies', 'Court equipment', 'Pool maintenance'],
      bestFor: ['billiards-hall', 'bowling-alley', 'sports-complex', 'resort-swimming-pool'],
      minimumOrder: '₱15,000 per order',
      paymentTerms: 'Cash, installment for major equipment',
      delivery: 'Freight and installation quoted per site',
      leadTime: '10 – 45 days',
      operatingHours: 'Mon – Sat, 9:00 AM – 6:00 PM',
      yearsOperating: 10,
    },
    {
      name: 'Agusan Events & Rentals Hub',
      trade: 'Event Furniture, AV & Styling',
      address: 'Baan Km. 3, Butuan City',
      barangay: 'Baan',
      phone: '+63 85 342 4478',
      email: 'agusaneventshub@gmail.com',
      lat: 8.9403,
      lng: 125.5288,
      specialties: ['Tables and chairs', 'Tents and staging', 'Styling props', 'Generators'],
      bestFor: ['events-place-function-hall', 'resort-swimming-pool', 'sports-complex'],
      minimumOrder: '₱5,000 per booking',
      paymentTerms: '50% reservation fee, balance before pull-out',
      delivery: 'Delivery and setup included within 15 km',
      leadTime: 'Book 3 – 14 days ahead',
      operatingHours: 'Mon – Sun, 8:00 AM – 6:00 PM',
      yearsOperating: 7,
    },
    {
      name: 'D&J Wholesale Center',
      trade: 'Beverages, Snacks & Personal Care',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 225 9900',
      email: 'dj.wholesale@yahoo.com',
      lat: 8.9501,
      lng: 125.5438,
      specialties: ['Softdrinks and juices', 'Snack packs', 'Disposables', 'Ice'],
      bestFor: ['videoke-ktv-bar', 'billiards-hall', 'gaming-internet-cafe', 'movie-cinema'],
      minimumOrder: '₱3,000 per delivery',
      paymentTerms: 'Cash, cheque for regular accounts',
      delivery: 'Free within Butuan proper',
      leadTime: '1 – 2 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:30 PM',
      yearsOperating: 12,
    },
  ],

  'manufacturing-production': [
    {
      name: 'Agri-Forest Supply Butuan',
      trade: 'Agricultural & Farming Supplies',
      address: 'Langihan Rd., Butuan City',
      barangay: 'Langihan',
      phone: '+63 85 342 7788',
      email: 'agriforest.butuan@gmail.com',
      lat: 8.9551,
      lng: 125.5622,
      specialties: ['Raw agricultural inputs', 'Coconut and abaca stock', 'Fertilizer', 'Sacks and packaging'],
      bestFor: ['food-processing', 'soap-detergent-production', 'candle-making'],
      minimumOrder: '₱8,000 per delivery',
      paymentTerms: 'Cash, 15-day terms for processors',
      delivery: 'Free within 12 km',
      leadTime: '2 – 7 days',
      operatingHours: 'Mon – Sat, 7:00 AM – 5:00 PM',
      yearsOperating: 24,
    },
    {
      name: 'Butuan Steel & Fabrication Supply',
      trade: 'Steel, Metal Stock & Welding',
      address: 'Bancasi, Butuan City',
      barangay: 'Bancasi',
      phone: '+63 85 341 9971',
      email: 'butuansteelsupply@gmail.com',
      lat: 8.9512,
      lng: 125.4821,
      specialties: ['Angle bars and tubing', 'GI sheets', 'Welding rods', 'Cutting services'],
      bestFor: ['metal-fabrication', 'hollow-blocks-construction-materials', 'furniture-making'],
      minimumOrder: '₱10,000 per delivery',
      paymentTerms: 'Cash, 30-day terms for contractors',
      delivery: 'Flatbed delivery, free above ₱30,000',
      leadTime: '1 – 7 days',
      operatingHours: 'Mon – Sat, 7:00 AM – 5:30 PM',
      yearsOperating: 27,
    },
    {
      name: 'Caraga Packaging & Labels',
      trade: 'Packaging, Bottles & Labels',
      address: 'Doongan, Butuan City',
      barangay: 'Doongan',
      phone: '+63 85 815 5528',
      email: 'caragapackaging@gmail.com',
      lat: 8.9644,
      lng: 125.5493,
      specialties: ['PET bottles and caps', 'Pouches and film', 'Label printing', 'Cartons'],
      bestFor: ['water-refilling-station', 'food-processing', 'soap-detergent-production', 'candle-making'],
      minimumOrder: '₱6,000 or one carton lot',
      paymentTerms: 'Cash, 15-day terms for regulars',
      delivery: 'Free within Butuan proper',
      leadTime: '3 – 14 days for printed labels',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:00 PM',
      yearsOperating: 11,
    },
    {
      name: 'Butuan Textile & Garments Supply',
      trade: 'Fabric, Trims & Sewing Machines',
      address: 'San Francisco St., Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 342 2264',
      email: 'butuantextilesupply@gmail.com',
      lat: 8.9459,
      lng: 125.5433,
      specialties: ['Bulk fabric', 'Thread and trims', 'Industrial sewing machines', 'Cutting tables'],
      bestFor: ['garments-sewing', 'furniture-making'],
      minimumOrder: '₱5,000 or one roll',
      paymentTerms: 'Cash, installment on machines',
      delivery: 'Free within 8 km',
      leadTime: '3 – 15 days',
      operatingHours: 'Mon – Sat, 8:30 AM – 6:00 PM',
      yearsOperating: 19,
    },
    {
      name: 'Caraga Cold Chain & Abattoir Supply',
      trade: 'Frozen Storage & Ice Production',
      address: 'Doongan Rd., Butuan City',
      barangay: 'Doongan',
      phone: '+63 85 815 3321',
      email: 'caragacoldchain@gmail.com',
      lat: 8.9631,
      lng: 125.5487,
      specialties: ['Blast freezing', 'Cold storage rental', 'Block and tube ice', 'Refrigerated transport'],
      bestFor: ['ice-plant', 'food-processing'],
      minimumOrder: '₱8,000 or 20 kg per item',
      paymentTerms: '30-day terms with deposit',
      delivery: 'Refrigerated van, free above ₱15,000',
      leadTime: '1 – 3 days',
      operatingHours: 'Mon – Sat, 6:00 AM – 5:00 PM',
      yearsOperating: 9,
    },
  ],

  'technology-digital': [
    {
      name: 'Caraga Electronics Wholesale',
      trade: 'Consumer Electronics & Components',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 815 7742',
      email: 'caraga.electronics@gmail.com',
      lat: 8.9548,
      lng: 125.5521,
      specialties: ['Components and boards', 'Mobile parts', 'Repair tools', 'Cables'],
      bestFor: ['electronics-repair', 'mobile-phone-shop-and-repair', 'it-services-computer-repair'],
      minimumOrder: '₱5,000 per delivery',
      paymentTerms: 'Cash, 15-day terms with deposit',
      delivery: 'Free within Butuan proper',
      leadTime: '2 – 5 days',
      operatingHours: 'Mon – Sat, 9:00 AM – 6:00 PM',
      yearsOperating: 8,
    },
    {
      name: 'Butuan IT Systems Distributor',
      trade: 'Computers, Servers & Networking',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Golden Ribbon',
      phone: '+63 85 342 6650',
      email: 'butuanitsystems@gmail.com',
      lat: 8.9516,
      lng: 125.5379,
      specialties: ['Workstations and servers', 'Switches and routers', 'Structured cabling', 'Licensing'],
      bestFor: ['it-services-computer-repair', 'software-development', 'bpo-call-center', 'web-design-studio'],
      minimumOrder: '₱20,000 per order',
      paymentTerms: '30-day terms for corporate accounts',
      delivery: 'Delivery and commissioning included',
      leadTime: '5 – 21 days',
      operatingHours: 'Mon – Fri, 8:30 AM – 5:30 PM',
      yearsOperating: 15,
    },
    {
      name: 'Caraga Security & Cash Handling Supply',
      trade: 'CCTV, Access Control & Alarms',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Golden Ribbon',
      phone: '+63 85 815 8823',
      email: 'caragasecuritysupply@gmail.com',
      lat: 8.9534,
      lng: 125.5461,
      specialties: ['IP camera kits', 'NVR systems', 'Access control', 'Alarm panels'],
      bestFor: ['cctv-security-installation', 'smart-home-installation', 'it-services-computer-repair'],
      minimumOrder: '₱8,000 per order',
      paymentTerms: 'Cash, financing available above ₱50,000',
      delivery: 'Delivery and installation quoted per site',
      leadTime: '3 – 10 days',
      operatingHours: 'Mon – Sat, 8:30 AM – 5:30 PM',
      yearsOperating: 13,
    },
    {
      name: 'Mindanao Drone & Imaging Supply',
      trade: 'Drones, Cameras & Survey Gear',
      address: 'Bancasi, Butuan City',
      barangay: 'Bancasi',
      phone: '+63 85 225 8817',
      email: 'mindanaodrone.supply@gmail.com',
      lat: 8.9503,
      lng: 125.4802,
      specialties: ['Survey drones', 'Gimbals and cameras', 'Batteries', 'Mapping software'],
      bestFor: ['drone-services', 'digital-marketing-agency', 'web-design-studio'],
      minimumOrder: '₱25,000 per order',
      paymentTerms: '50% down payment, balance on release',
      delivery: 'Courier from Cebu hub, insured',
      leadTime: '7 – 21 days',
      operatingHours: 'Mon – Fri, 9:00 AM – 5:00 PM',
      yearsOperating: 5,
    },
    {
      name: 'Butuan Office Systems Supply',
      trade: 'Office Equipment & Consumables',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Poblacion',
      phone: '+63 85 342 9915',
      email: 'butuanofficesystems@gmail.com',
      lat: 8.9509,
      lng: 125.5423,
      specialties: ['Headsets and peripherals', 'Workstation furniture', 'Printers', 'Consumables'],
      bestFor: ['bpo-call-center', 'software-development', 'digital-marketing-agency'],
      minimumOrder: '₱2,500 per delivery',
      paymentTerms: 'Cash, 30-day terms for corporate accounts',
      delivery: 'Free within Butuan proper',
      leadTime: 'Same day to 3 days',
      operatingHours: 'Mon – Sat, 8:00 AM – 5:30 PM',
      yearsOperating: 14,
    },
  ],

  'construction-building': [
    {
      name: 'Metro Butuan Construction Depot',
      trade: 'Cement, Aggregates & Rebar',
      address: 'Libertad, Butuan City',
      barangay: 'Libertad',
      phone: '+63 85 341 5502',
      email: 'metrobutuan.construction@gmail.com',
      lat: 8.9604,
      lng: 125.5298,
      specialties: ['Cement', 'Sand and gravel', 'Rebar', 'Hollow blocks'],
      bestFor: ['general-contractor', 'masonry-carpentry', 'roofing-services', 'steel-fabrication-works'],
      minimumOrder: '₱15,000 or one truckload',
      paymentTerms: '30-day terms for licensed contractors',
      delivery: 'Dump truck delivery quoted per volume',
      leadTime: '1 – 5 days',
      operatingHours: 'Mon – Sat, 7:00 AM – 5:00 PM',
      yearsOperating: 25,
    },
    {
      name: 'Butuan Hardware & Industrial Supply',
      trade: 'Hardware, Tools & Fixtures',
      address: 'Montilla Blvd, Butuan City',
      barangay: 'Golden Ribbon',
      phone: '+63 85 341 8890',
      email: 'butuanhardware@gmail.com',
      lat: 8.9527,
      lng: 125.5372,
      specialties: ['Power tools', 'Plumbing fittings', 'Electrical supplies', 'Paint and finishes'],
      bestFor: ['plumbing-services', 'electrical-contractor', 'painting-services', 'general-contractor'],
      minimumOrder: '₱7,500 per delivery',
      paymentTerms: 'Cash, cheque, 15-day terms',
      delivery: 'Free within 10 km',
      leadTime: '1 – 5 days depending on stock',
      operatingHours: 'Mon – Sat, 7:30 AM – 6:00 PM',
      yearsOperating: 26,
    },
    {
      name: 'Butuan Steel & Fabrication Supply',
      trade: 'Steel, Roofing & Welding Supply',
      address: 'Bancasi, Butuan City',
      barangay: 'Bancasi',
      phone: '+63 85 341 9971',
      email: 'butuansteelsupply@gmail.com',
      lat: 8.9512,
      lng: 125.4821,
      specialties: ['Roofing sheets', 'Angle bars and tubing', 'Welding consumables', 'Cutting and bending'],
      bestFor: ['steel-fabrication-works', 'roofing-services', 'general-contractor'],
      minimumOrder: '₱10,000 per delivery',
      paymentTerms: 'Cash, 30-day terms for contractors',
      delivery: 'Flatbed delivery, free above ₱30,000',
      leadTime: '1 – 7 days',
      operatingHours: 'Mon – Sat, 7:00 AM – 5:30 PM',
      yearsOperating: 27,
    },
    {
      name: 'Caraga Equipment Rental Yard',
      trade: 'Heavy Equipment & Tool Rental',
      address: 'Ampayon, Butuan City',
      barangay: 'Ampayon',
      phone: '+63 85 815 4470',
      email: 'caragaequipmentrental@gmail.com',
      lat: 8.9583,
      lng: 125.5981,
      specialties: ['Backhoes and loaders', 'Scaffolding', 'Concrete mixers', 'Generators'],
      bestFor: ['equipment-rental', 'general-contractor', 'landscaping', 'masonry-carpentry'],
      minimumOrder: 'One-day minimum rental',
      paymentTerms: 'Deposit plus daily rate, billed weekly',
      delivery: 'Hauling to site quoted separately',
      leadTime: 'Book 2 – 7 days ahead',
      operatingHours: 'Mon – Sat, 7:00 AM – 6:00 PM',
      yearsOperating: 12,
    },
    {
      name: 'Agusan Interiors & Finishes',
      trade: 'Tiles, Fixtures & Interior Finishes',
      address: 'J.C. Aquino Ave., Butuan City',
      barangay: 'Villa Kananga',
      phone: '+63 85 342 3315',
      email: 'agusaninteriors@gmail.com',
      lat: 8.9563,
      lng: 125.5544,
      specialties: ['Floor and wall tiles', 'Sanitary fixtures', 'Ceiling systems', 'Lighting'],
      bestFor: ['interior-design', 'painting-services', 'general-contractor', 'landscaping'],
      minimumOrder: '₱8,000 per delivery',
      paymentTerms: 'Cash, 15-day terms for designers',
      delivery: 'Free within 10 km',
      leadTime: '3 – 21 days for special orders',
      operatingHours: 'Mon – Sat, 8:00 AM – 6:00 PM',
      yearsOperating: 10,
    },
  ],
}
